# Generated by Django 5.2.2 on 2025-06-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_recommendation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobCategory',
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
